name: xml_parser
description: An unopinionated XML parser that can read, traverse, modify, and write XML documents.
version: 2.0.0
homepage: https://github.com/james-alex/xml_parser

environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  collection: ^1.15.0
  html_character_entities: ^1.0.0+1
  http: ">=0.13.0 <2.0.0"
  recursive_regex: ^1.0.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.4
  pedantic: ^1.11.0
